version: "3.9"
services:
  api:
    build: .
    command: fastapi run app/main.py --port 8000 --host 0.0.0.0
    env_file: .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  celery-worker:
    build: .
    command: celery -A app.background.celery_app worker --loglevel=info --concurrency=4
    env_file: .env
    restart: unless-stopped

  celery-beat:
    build: .
    command: celery -A app.background.celery_app beat --loglevel=info
    env_file: .env
    restart: unless-stopped
