"""add integration models

Revision ID: 1166c9854b37
Revises: 42dde97ce85c
Create Date: 2026-03-30 09:06:58.792804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1166c9854b37'
down_revision: Union[str, None] = '42dde97ce85c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_providers',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('auth_method', sa.Enum('oauth2', 'api_key', 'webhook_secret', 'basic', name='auth_method'), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('oauth_scopes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_providers_key'), 'integration_providers', ['key'], unique=True)
    op.create_table('workspace_integrations',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('connected', 'inactive', 'error', 'disconnected', name='integration_status'), nullable=False),
    sa.Column('access_token_enc', sa.String(), nullable=True),
    sa.Column('refresh_token_enc', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_key_enc', sa.String(), nullable=True),
    sa.Column('endpoint_url', sa.String(), nullable=True),
    sa.Column('signing_secret_enc', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('installed_by', sa.UUID(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['installed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['integration_providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'provider_id', name='uq_workspace_provider')
    )
    op.create_index(op.f('ix_workspace_integrations_provider_id'), 'workspace_integrations', ['provider_id'], unique=False)
    op.create_index(op.f('ix_workspace_integrations_workspace_id'), 'workspace_integrations', ['workspace_id'], unique=False)
    op.create_table('campaign_integrations',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('workspace_integration_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_integration_id'], ['workspace_integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'workspace_integration_id', name='uq_campaign_workspace_integration')
    )
    op.create_index(op.f('ix_campaign_integrations_campaign_id'), 'campaign_integrations', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_integrations_workspace_integration_id'), 'campaign_integrations', ['workspace_integration_id'], unique=False)
    # Seed data
    integration_providers = sa.table(
        'integration_providers',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('display_name', sa.String(), nullable=False),
        sa.Column('icon_url', sa.String(), nullable=True),
        sa.Column('auth_method', sa.Enum('oauth2', 'api_key', 'webhook_secret', 'basic', name='auth_method'), nullable=False),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('oauth_scopes', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
    )

    import uuid
    op.bulk_insert(
        integration_providers,
        [
            {"id": uuid.uuid4(), "key": "hubspot",    "display_name": "HubSpot",         "auth_method": "oauth2",         "category": "CRM",           "is_active": True},
            {"id": uuid.uuid4(), "key": "salesforce", "display_name": "Salesforce",      "auth_method": "oauth2",         "category": "CRM",           "is_active": True},
            {"id": uuid.uuid4(), "key": "slack",      "display_name": "Slack",           "auth_method": "oauth2",         "category": "Communication", "is_active": True},
            {"id": uuid.uuid4(), "key": "google_cal", "display_name": "Google Calendar", "auth_method": "oauth2",         "category": "Scheduling",    "is_active": True},
            {"id": uuid.uuid4(), "key": "zapier",     "display_name": "Zapier",          "auth_method": "api_key",        "category": "Automation",    "is_active": True},
            {"id": uuid.uuid4(), "key": "make",       "display_name": "Make",            "auth_method": "api_key",        "category": "Automation",    "is_active": True},
            {"id": uuid.uuid4(), "key": "webhooks",   "display_name": "Custom Webhooks", "auth_method": "webhook_secret", "category": "Developer",     "is_active": True},
            {"id": uuid.uuid4(), "key": "pipedrive",  "display_name": "Pipedrive",       "auth_method": "oauth2",         "category": "CRM",           "is_active": True},
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_integrations_workspace_integration_id'), table_name='campaign_integrations')
    op.drop_index(op.f('ix_campaign_integrations_campaign_id'), table_name='campaign_integrations')
    op.drop_table('campaign_integrations')
    op.drop_index(op.f('ix_workspace_integrations_workspace_id'), table_name='workspace_integrations')
    op.drop_index(op.f('ix_workspace_integrations_provider_id'), table_name='workspace_integrations')
    op.drop_table('workspace_integrations')
    op.drop_index(op.f('ix_integration_providers_key'), table_name='integration_providers')
    op.drop_table('integration_providers')
    # ### end Alembic commands ###
