"""add_campaign_daily_stats

Revision ID: 1231285e5110
Revises: 1e4a2e2e5665
Create Date: 2026-04-01 08:58:08.000799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1231285e5110'
down_revision: Union[str, None] = '1e4a2e2e5665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_daily_stats', sa.Column('contacts_opted_out', sa.Integer(), nullable=False))
    op.drop_constraint('uq_campaign_daily_stats', 'campaign_daily_stats', type_='unique')
    op.create_unique_constraint('campaign_daily_stats_unique', 'campaign_daily_stats', ['campaign_id', 'stat_date'])
    op.create_index('idx_campaign_daily_stats_campaign', 'campaign_daily_stats', ['campaign_id', 'stat_date'], unique=False)
    op.create_index('idx_campaign_daily_stats_workspace', 'campaign_daily_stats', ['workspace_id', 'stat_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_campaign_daily_stats_workspace', table_name='campaign_daily_stats')
    op.drop_index('idx_campaign_daily_stats_campaign', table_name='campaign_daily_stats')
    op.drop_constraint('campaign_daily_stats_unique', 'campaign_daily_stats', type_='unique')
    op.create_unique_constraint('uq_campaign_daily_stats', 'campaign_daily_stats', ['campaign_id', 'stat_date'])
    op.drop_column('campaign_daily_stats', 'contacts_opted_out')
    # ### end Alembic commands ###
