"""add_stats_and_webhook_models

Revision ID: 1e4a2e2e5665
Revises: 22859bfe742c
Create Date: 2026-03-31 10:03:53.357928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e4a2e2e5665'
down_revision: Union[str, None] = '22859bfe742c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_webhook_endpoints',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('events', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('signing_secret_enc', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_retries', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_webhook_endpoints_workspace_id'), 'workspace_webhook_endpoints', ['workspace_id'], unique=False)
    op.create_table('campaign_daily_stats',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('calls_total', sa.Integer(), nullable=False),
    sa.Column('calls_completed', sa.Integer(), nullable=False),
    sa.Column('calls_failed', sa.Integer(), nullable=False),
    sa.Column('calls_no_answer', sa.Integer(), nullable=False),
    sa.Column('calls_busy', sa.Integer(), nullable=False),
    sa.Column('calls_voicemail', sa.Integer(), nullable=False),
    sa.Column('calls_transferred', sa.Integer(), nullable=False),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('avg_duration_seconds', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('avg_latency_p50_ms', sa.Integer(), nullable=True),
    sa.Column('avg_latency_p95_ms', sa.Integer(), nullable=True),
    sa.Column('cost_telephony_cents', sa.Integer(), nullable=False),
    sa.Column('cost_llm_cents', sa.Integer(), nullable=False),
    sa.Column('cost_tts_cents', sa.Integer(), nullable=False),
    sa.Column('cost_stt_cents', sa.Integer(), nullable=False),
    sa.Column('outcome_booked_demo', sa.Integer(), nullable=False),
    sa.Column('outcome_interested', sa.Integer(), nullable=False),
    sa.Column('outcome_not_interested', sa.Integer(), nullable=False),
    sa.Column('outcome_callback', sa.Integer(), nullable=False),
    sa.Column('sentiment_positive', sa.Integer(), nullable=False),
    sa.Column('sentiment_neutral', sa.Integer(), nullable=False),
    sa.Column('sentiment_negative', sa.Integer(), nullable=False),
    sa.Column('contacts_called', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'stat_date', name='uq_campaign_daily_stats')
    )
    op.create_index(op.f('ix_campaign_daily_stats_agent_id'), 'campaign_daily_stats', ['agent_id'], unique=False)
    op.create_index(op.f('ix_campaign_daily_stats_campaign_id'), 'campaign_daily_stats', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_daily_stats_stat_date'), 'campaign_daily_stats', ['stat_date'], unique=False)
    op.create_index(op.f('ix_campaign_daily_stats_workspace_id'), 'campaign_daily_stats', ['workspace_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('endpoint_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'retrying', name='webhook_delivery_status'), nullable=False),
    sa.Column('attempt_number', sa.SmallInteger(), nullable=False),
    sa.Column('http_status_code', sa.SmallInteger(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['endpoint_id'], ['workspace_webhook_endpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_endpoint_id'), 'webhook_deliveries', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_workspace_id'), 'webhook_deliveries', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_deliveries_workspace_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_endpoint_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_campaign_daily_stats_workspace_id'), table_name='campaign_daily_stats')
    op.drop_index(op.f('ix_campaign_daily_stats_stat_date'), table_name='campaign_daily_stats')
    op.drop_index(op.f('ix_campaign_daily_stats_campaign_id'), table_name='campaign_daily_stats')
    op.drop_index(op.f('ix_campaign_daily_stats_agent_id'), table_name='campaign_daily_stats')
    op.drop_table('campaign_daily_stats')
    op.drop_index(op.f('ix_workspace_webhook_endpoints_workspace_id'), table_name='workspace_webhook_endpoints')
    op.drop_table('workspace_webhook_endpoints')
    # ### end Alembic commands ###
