"""add_call_models_and_webhook_secret

Revision ID: 22859bfe742c
Revises: 1166c9854b37
Create Date: 2026-03-31 09:53:03.760826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22859bfe742c'
down_revision: Union[str, None] = '1166c9854b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('phone_number_id', sa.UUID(), nullable=True),
    sa.Column('elevenlabs_conversation_id', sa.String(), nullable=True),
    sa.Column('kb_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='call_direction'), nullable=False),
    sa.Column('from_number', sa.String(), nullable=False),
    sa.Column('to_number', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'ringing', 'in_progress', 'completed', 'failed', 'no_answer', 'busy', 'voicemail', 'transferred', 'timeout', name='call_status'), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('sentiment', sa.Enum('positive', 'neutral', 'negative', name='sentiment'), nullable=True),
    sa.Column('is_voicemail', sa.Boolean(), nullable=False),
    sa.Column('was_transferred', sa.Boolean(), nullable=False),
    sa.Column('transfer_destination', sa.String(), nullable=True),
    sa.Column('recording_url', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('cost_telephony_cents', sa.Integer(), nullable=False),
    sa.Column('cost_llm_cents', sa.Integer(), nullable=False),
    sa.Column('cost_tts_cents', sa.Integer(), nullable=False),
    sa.Column('cost_stt_cents', sa.Integer(), nullable=False),
    sa.Column('latency_p50_ms', sa.Integer(), nullable=True),
    sa.Column('latency_p95_ms', sa.Integer(), nullable=True),
    sa.Column('latency_p99_ms', sa.Integer(), nullable=True),
    sa.Column('retry_number', sa.SmallInteger(), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('raw_provider_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kb_snapshot_id'], ['campaign_kb_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_agent_id'), 'calls', ['agent_id'], unique=False)
    op.create_index(op.f('ix_calls_campaign_id'), 'calls', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_calls_contact_id'), 'calls', ['contact_id'], unique=False)
    op.create_index(op.f('ix_calls_elevenlabs_conversation_id'), 'calls', ['elevenlabs_conversation_id'], unique=True)
    op.create_index(op.f('ix_calls_phone_number_id'), 'calls', ['phone_number_id'], unique=False)
    op.create_index(op.f('ix_calls_workspace_id'), 'calls', ['workspace_id'], unique=False)
    op.create_table('call_collected_data',
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('field_key', sa.String(), nullable=False),
    sa.Column('field_value', sa.String(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_collected_data_call_id'), 'call_collected_data', ['call_id'], unique=False)
    op.create_table('call_evaluations',
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('criteria', sa.String(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('evaluated_by', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_evaluations_call_id'), 'call_evaluations', ['call_id'], unique=False)
    op.create_table('call_transcripts',
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.SmallInteger(), nullable=False),
    sa.Column('speaker', sa.Enum('agent', 'user', 'tool', 'system', name='transcript_speaker'), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('timestamp_secs', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('tool_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'sequence', name='uq_call_transcripts_sequence')
    )
    op.create_index(op.f('ix_call_transcripts_call_id'), 'call_transcripts', ['call_id'], unique=False)
    op.add_column('workspaces', sa.Column('elevenlabs_webhook_secret_enc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'elevenlabs_webhook_secret_enc')
    op.drop_index(op.f('ix_call_transcripts_call_id'), table_name='call_transcripts')
    op.drop_table('call_transcripts')
    op.drop_index(op.f('ix_call_evaluations_call_id'), table_name='call_evaluations')
    op.drop_table('call_evaluations')
    op.drop_index(op.f('ix_call_collected_data_call_id'), table_name='call_collected_data')
    op.drop_table('call_collected_data')
    op.drop_index(op.f('ix_calls_workspace_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_phone_number_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_elevenlabs_conversation_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_contact_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_campaign_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_agent_id'), table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###
