"""add_feeder_task_id_to_campaigns

Revision ID: 2fa7d430f250
Revises: dd6cd1623189
Create Date: 2026-04-01 10:18:12.385721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fa7d430f250'
down_revision: Union[str, None] = 'dd6cd1623189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('feeder_task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'feeder_task_id')
    # ### end Alembic commands ###
