"""Add Knowledge and Contact models

Revision ID: 42dde97ce85c
Revises: 45152f213b32
Create Date: 2026-03-30 08:34:03.076887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42dde97ce85c'
down_revision: Union[str, None] = '45152f213b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table('campaigns',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('goal_description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'live', 'paused', 'completed', 'archived', name='campaign_status'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('phone_number_id', sa.UUID(), nullable=True),
    sa.Column('kb_sync_status', sa.Enum('pending', 'syncing', 'synced', 'failed', name='kb_sync_status'), nullable=False),
    sa.Column('kb_last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('schedule_days', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('schedule_start_time', sa.Time(), nullable=False),
    sa.Column('schedule_end_time', sa.Time(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_delay_minutes', sa.Integer(), nullable=False),
    sa.Column('retry_on_outcomes', sa.ARRAY(sa.Enum('no_answer', 'busy', 'voicemail', 'failed', 'timeout', name='retry_on_outcome')), nullable=False),
    sa.Column('dnc_check_enabled', sa.Boolean(), nullable=False),
    sa.Column('record_calls', sa.Boolean(), nullable=False),
    sa.Column('tcpa_mode', sa.Boolean(), nullable=False),
    sa.Column('voicemail_detection', sa.Boolean(), nullable=False),
    sa.Column('leave_voicemail', sa.Boolean(), nullable=False),
    sa.Column('caller_id_display_name', sa.String(), nullable=True),
    sa.Column('contacts_total', sa.Integer(), nullable=False),
    sa.Column('contacts_called', sa.Integer(), nullable=False),
    sa.Column('contacts_remaining', sa.Integer(), nullable=False),
    sa.Column('calls_successful', sa.Integer(), nullable=False),
    sa.Column('calls_failed', sa.Integer(), nullable=False),
    sa.Column('total_spend_cents', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_campaigns_agent_one_active', 'campaigns', ['agent_id'], unique=True, postgresql_where=sa.text("status IN ('live', 'scheduled') AND agent_id IS NOT NULL AND deleted_at IS NULL"))
    op.create_index(op.f('ix_campaigns_agent_id'), 'campaigns', ['agent_id'], unique=False)
    op.create_index(op.f('ix_campaigns_phone_number_id'), 'campaigns', ['phone_number_id'], unique=False)
    op.create_index(op.f('ix_campaigns_workspace_id'), 'campaigns', ['workspace_id'], unique=False)
    op.create_table('campaign_kb_snapshots',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by', sa.Enum('paused', 'completed', 'agent_reassigned', name='kb_snapshot_trigger'), nullable=False),
    sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('elevenlabs_agent_id', sa.String(), nullable=True),
    sa.Column('campaign_status_at_snapshot', sa.Enum('draft', 'scheduled', 'live', 'paused', 'completed', 'archived', name='campaign_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_kb_snapshots_campaign_id'), 'campaign_kb_snapshots', ['campaign_id'], unique=False)
    op.create_table('contacts',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'calling', 'called', 'failed', 'opted_out', 'do_not_call', name='contact_status'), nullable=False),
    sa.Column('retry_count', sa.SmallInteger(), nullable=False),
    sa.Column('last_called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opted_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_dnc', sa.Boolean(), nullable=False),
    sa.Column('last_outcome', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contacts_campaign_phone_unique', 'contacts', ['campaign_id', 'phone'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_contacts_search', 'contacts', ['full_name', 'phone'], unique=False, postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops', 'phone': 'gin_trgm_ops'})
    op.create_index(op.f('ix_contacts_campaign_id'), 'contacts', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_contacts_phone'), 'contacts', ['phone'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('doc_type', sa.Enum('pdf', 'docx', 'txt', 'csv', 'url_scrape', 'api_sync', name='doc_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'ready', 'failed', name='doc_status'), nullable=False),
    sa.Column('elevenlabs_kb_id', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('chunk_size_tokens', sa.Integer(), nullable=False),
    sa.Column('overlap_tokens', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_campaign_id'), 'knowledge_documents', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_documents_campaign_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_contacts_phone'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_campaign_id'), table_name='contacts')
    op.drop_index('idx_contacts_search', table_name='contacts', postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops', 'phone': 'gin_trgm_ops'})
    op.drop_index('idx_contacts_campaign_phone_unique', table_name='contacts', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('contacts')
    op.drop_index(op.f('ix_campaign_kb_snapshots_campaign_id'), table_name='campaign_kb_snapshots')
    op.drop_table('campaign_kb_snapshots')
    op.drop_index(op.f('ix_campaigns_workspace_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_phone_number_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_agent_id'), table_name='campaigns')
    op.drop_index('idx_campaigns_agent_one_active', table_name='campaigns', postgresql_where=sa.text("status IN ('live', 'scheduled') AND agent_id IS NOT NULL AND deleted_at IS NULL"))
    op.drop_table('campaigns')
    # ### end Alembic commands ###
