"""add phone numbers

Revision ID: 45152f213b32
Revises: 2c8185cecf33
Create Date: 2026-03-29 22:04:48.561032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45152f213b32'
down_revision: Union[str, None] = '2c8185cecf33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_numbers',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('friendly_name', sa.String(), nullable=True),
    sa.Column('provider', sa.Enum('twilio', 'vonage', 'telnyx', 'sip_trunk', 'elevenlabs', name='phone_provider'), nullable=False),
    sa.Column('elevenlabs_number_id', sa.String(), nullable=True),
    sa.Column('provider_sid', sa.String(), nullable=True),
    sa.Column('number_type', sa.Enum('local', 'toll_free', 'mobile', 'sip', name='phone_number_type'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'released', 'porting', name='phone_number_status'), nullable=False),
    sa.Column('sip_server', sa.String(), nullable=True),
    sa.Column('sip_username', sa.String(), nullable=True),
    sa.Column('sip_password_enc', sa.String(), nullable=True),
    sa.Column('sip_port', sa.SmallInteger(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('cnam_registered', sa.Boolean(), nullable=False),
    sa.Column('calls_made', sa.Integer(), nullable=False),
    sa.Column('monthly_cost_cents', sa.Integer(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'number', name='uq_workspace_phone_number')
    )
    op.create_index(op.f('ix_phone_numbers_workspace_id'), 'phone_numbers', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_numbers_workspace_id'), table_name='phone_numbers')
    op.drop_table('phone_numbers')
    # ### end Alembic commands ###
